version: '2'

services:
  rabbitmq:
    image: rabbitmq:latest
    cap_add:
      - SYS_PTRACE
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_ERLANG_COOKIE=secretcookie
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq
    ports:
      - '0.0.0.0::5672'
      - '0.0.0.0::15672'
  publisher:
    image: bitnami/python
    links:
      - rabbitmq
    volumes:
      - './publish.py:/tmp/commands.py'
      - './coverage_script.sh:/tmp/coverage_script.sh'
    command: "sleep infinity"
  consumer:
    image: bitnami/python
    links:
      - rabbitmq
    volumes:
      - './consume.py:/tmp/commands.py'
      - './coverage_script.sh:/tmp/coverage_script.sh'
    command: "sleep infinity"

networks:
  rabbitmq-network:
    driver: bridge