version: '2'
services:
  cassandra:
    image: ${CASSANDRA_IMAGE_REPOSITORY}:${CASSANDRA_IMAGE_TAG}
    ports:
      - ::7000
      - ::9042
    volumes:
      - cassandra_data:/official
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    cap_add:
      - SYS_PTRACE
 # cassandra2:
 #   image: docker.io/library/cassandra:4.0
 #   ports:
 #     - 7001:7000
 #     - 9043:9042
 #   volumes:
 #     - cassandra2_data:/official
 #   environment:
 #     - CASSANDRA_SEEDS=cassandra,cassandra2
 #     - CASSANDRA_CLUSTER_NAME=cassandra-cluster
 #     - CASSANDRA_PASSWORD=cassandra
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
 #     - MAX_HEAP_SIZE=2G
 #     - HEAP_NEWSIZE=200M
volumes:
  cassandra_data:
    driver: local
#  cassandra2_data:
#    driver: local
