version: '2'

services:
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE_REPOSITORY}:${ELASTICSEARCH_IMAGE_TAG}
    user: elasticsearch
    cap_add:
      - SYS_PTRACE
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch_data:/var/lib/elasticsearch/data'
volumes:
  elasticsearch_data:
    driver: local
