version: '2'

services:
  elasticsearch:
    image: ${ELASTICSEARCH_IMAGE_REPOSITORY}:${ELASTICSEARCH_IMAGE_TAG}
    container_name: es-container
    user: elasticsearch
    cap_add:
      - SYS_PTRACE
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - xpack.ml.enabled=false
      - xpack.security.enabled=false
      - "discovery.type=single-node" 
    networks:
      - es-net
    volumes:
      - 'elasticsearch_data:/var/lib/elasticsearch/data'

networks:
  es-net:
    driver: bridge
    
volumes:
  elasticsearch_data:
    driver: local
