---
services:

  load-balancer:
    image: nginx:latest-load-balancer
    container_name: nginx-lb
    cap_add: [ SYS_PTRACE ]
    ports:
      - "80:80"
    volumes:
      - ./nginx-load-balancer/nginx.conf:/etc/nginx/nginx.conf

  web-server:
    image: nginx:latest-web-server
    container_name: web-server
    cap_add: [ SYS_PTRACE ]
    ports:
      - "3000:80"
    volumes:
      - ./web-server/build:/usr/share/nginx/html

  api-server1:
    image: api-server:latest
    build: api-server
    container_name: api-server1
    environment:
      - "SERVER_ID=Api Server #1"
    ports:
      - "9000:80"
    volumes:
      - ./api-server:/rf
  
  api-server2:
    image: api-server:latest
    build: api-server
    container_name: api-server1
    container_name: api-server2
    environment:
      - "SERVER_ID=Api Server #2"
    ports:
      - "8000:80"
    volumes:
      - ./api-server:/rf

