version: '3.6'
services:
  web:
    image: ${GITLABCE_IMAGE_REPOSITORY}:${GITLABCE_IMAGE_TAG}
    privileged: true
    cap_add:
      - SYS_PTRACE
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
        gitlab_rails['initial_root_password'] = 'adminadmin'
    ports:
      - '6680:80'
      - '6643:443'
      - '6622:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'